using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace ObsWebSocket.Codegen.Tasks.Generation;

internal static partial class Emitter
{
    /// <summary>
    /// Emits handle accessors on every event payload and response that already carries a uuid.
    /// </summary>
    /// <remarks>
    /// These are the handles that cost nothing. An event announcing a scene change already says
    /// which scene, by uuid, so acting on it needs no lookup and the result is immune to a rename
    /// that happens between the event arriving and the next request going out. Without them the
    /// caller reads <c>e.EventData.SceneName</c> and addresses the scene by name again, which is
    /// the round trip and the race the uuid was there to avoid.
    /// </remarks>
    public static void GeneratePayloadHandles(
        SourceProductionContext context,
        ProtocolDefinition protocol
    )
    {
        StringBuilder builder = new();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("using System;");
        builder.AppendLine($"using {GeneratedCommonNamespace};");
        builder.AppendLine();
        builder.AppendLine($"namespace {ExtensionsNamespace};");
        builder.AppendLine();
        builder.AppendLine("/// <summary>");
        builder.AppendLine(
            "/// Handles for the things an event or a response already identifies by uuid."
        );
        builder.AppendLine("/// </summary>");
        builder.AppendLine("public static class ObsWebSocketPayloadHandles");
        builder.AppendLine("{");

        int emitted = 0;

        if (protocol.Events is not null)
        {
            foreach (
                OBSEvent definition in protocol.Events.OrderBy(
                    e => e.EventType,
                    StringComparer.Ordinal
                )
            )
            {
                emitted += EmitAccessors(
                    builder,
                    $"{GeneratedEventsNamespace}.{SanitizeIdentifier(definition.EventType)}Payload",
                    "payload",
                    definition.DataFields
                );
            }
        }

        if (protocol.Requests is not null)
        {
            foreach (
                RequestDefinition request in protocol.Requests.OrderBy(
                    r => r.RequestType,
                    StringComparer.Ordinal
                )
            )
            {
                if (request.ResponseFields is null || request.ResponseFields.Count == 0)
                {
                    continue;
                }

                emitted += EmitAccessors(
                    builder,
                    $"{GeneratedResponsesNamespace}.{SanitizeIdentifier(request.RequestType)}ResponseData",
                    "response",
                    request.ResponseFields
                );
            }
        }

        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine($"// Handles reachable without a lookup: {emitted}");

        context.AddSource(
            "ObsWebSocketClient.PayloadHandles.g.cs",
            SourceText.From(builder.ToString(), Encoding.UTF8)
        );
    }

    /// <summary>
    /// Emits one extension block for a payload, holding an accessor per uuid it carries.
    /// </summary>
    private static int EmitAccessors(
        StringBuilder builder,
        string payloadType,
        string parameterName,
        IReadOnlyList<FieldDefinition>? fields
    )
    {
        if (fields is null || fields.Count == 0)
        {
            return 0;
        }

        Dictionary<string, FieldDefinition> byName = new(StringComparer.Ordinal);
        foreach (FieldDefinition field in fields)
        {
            byName[field.ValueName] = field;
        }

        List<(
            string Accessor,
            string HandleType,
            string Expression,
            bool Nullable,
            string Doc
        )> accessors = [];

        foreach (FieldDefinition field in fields)
        {
            string name = field.ValueName;
            if (!name.EndsWith("Uuid", StringComparison.Ordinal))
            {
                continue;
            }

            string role = name.Substring(0, name.Length - "Uuid".Length);
            string? handleType = HandleTypeForRole(role);
            if (handleType is null)
            {
                continue;
            }

            string property = SanitizeIdentifier(ToPascalCase(name));
            string accessor = SanitizeIdentifier(ToPascalCase(role));
            bool nullable =
                field.ValueOptional == true || DescriptionAllowsNull(field.ValueDescription);

            accessors.Add(
                (
                    accessor,
                    handleType,
                    $"{handleType}.FromUuid({parameterName}.{property})",
                    nullable,
                    $"The {DescribeRole(role)} this message identifies, addressed by uuid so a rename cannot move it."
                )
            );
        }

        // A scene item needs the scene as well as the id, and both travel together when they
        // travel at all.
        if (byName.ContainsKey("sceneItemId") && byName.ContainsKey("sceneUuid"))
        {
            FieldDefinition idField = byName["sceneItemId"];
            bool nullable =
                idField.ValueOptional == true || DescriptionAllowsNull(idField.ValueDescription);
            accessors.Add(
                (
                    "SceneItem",
                    "SceneItemHandle",
                    $"SceneItemHandle.For(SceneHandle.FromUuid({parameterName}.SceneUuid), {parameterName}.SceneItemId)",
                    nullable,
                    "The scene item this message is about, ready to act on without a lookup."
                )
            );
        }

        if (accessors.Count == 0)
        {
            return 0;
        }

        builder.AppendLine($"    extension({payloadType} {parameterName})");
        builder.AppendLine("    {");
        foreach (
            (
                string accessor,
                string handleType,
                string expression,
                bool nullable,
                string doc
            ) in accessors
        )
        {
            builder.AppendLine($"        /// <summary>{doc}</summary>");
            if (nullable)
            {
                string source = expression[(expression.IndexOf('(') + 1)..^1];
                builder.AppendLine($"        public {handleType}? {accessor} =>");
                builder.AppendLine(
                    $"            string.IsNullOrEmpty({FirstArgument(source)}) ? null : {expression};"
                );
            }
            else
            {
                builder.AppendLine($"        public {handleType} {accessor} => {expression};");
            }

            builder.AppendLine();
        }

        builder.AppendLine("    }");
        builder.AppendLine();
        return accessors.Count;
    }

    /// <summary>The uuid expression a null check has to look at.</summary>
    private static string FirstArgument(string arguments)
    {
        int comma = arguments.IndexOf(',');
        return comma < 0 ? arguments : arguments[..comma].Trim();
    }

    /// <summary>
    /// The handle type a <c>{role}Uuid</c> field yields, or null when the role is not something a
    /// request can address.
    /// </summary>
    /// <remarks>
    /// <c>transitionUuid</c> appears on four events and one response, but no request accepts one,
    /// so a handle for it could not be used for anything. It is left out until the protocol grows
    /// somewhere to send it.
    /// </remarks>
    private static string? HandleTypeForRole(string role) =>
        role switch
        {
            "scene" or "currentProgramScene" or "currentPreviewScene" or "destinationScene" =>
                "SceneHandle",
            "input" => "InputHandle",
            "source" => "SourceHandle",
            "canvas" => "CanvasHandle",
            _ => null,
        };

    private static string DescribeRole(string role) =>
        role switch
        {
            "currentProgramScene" => "program scene",
            "currentPreviewScene" => "preview scene",
            "destinationScene" => "destination scene",
            _ => role,
        };
}
