using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace ObsWebSocket.Codegen.Tasks.Generation;

internal static partial class Emitter
{
    /// <summary>
    /// Emits, for each kind of thing OBS can address, a type carrying every request about it, with
    /// the name, uuid and canvas fields already supplied by the handle.
    /// </summary>
    /// <remarks>
    /// These are deliberately not overloads of the existing request methods. A method pair of
    /// <c>M(XRequestData)</c> and <c>M(XHandle)</c> is ambiguous the moment a caller writes
    /// <c>M(new(...))</c>, because a target typed <c>new</c> is convertible to either, and that
    /// idiom is all over the existing surface and the README. Giving the handle form its own type
    /// keeps both usable.
    /// <para>
    /// The set is derived from the field shape rather than listed, so a request added upstream
    /// that takes a scene appears here the day the definition lands.
    /// </para>
    /// </remarks>
    public static void GenerateHandleOverloads(
        SourceProductionContext context,
        ProtocolDefinition protocol
    )
    {
        if (protocol.Requests is null)
        {
            return;
        }

        // Each request belongs to the thing it is primarily about, which is its first reference.
        Dictionary<
            string,
            List<(RequestDefinition Request, IReadOnlyList<EntityReference> Refs)>
        > byKind = new(StringComparer.Ordinal);

        foreach (RequestDefinition request in protocol.Requests)
        {
            IReadOnlyList<EntityReference> references = EntityReferenceTable.Find(
                request.RequestFields
            );
            if (references.Count == 0)
            {
                continue;
            }

            string kind = references[0].Kind;
            if (!byKind.TryGetValue(kind, out var list))
            {
                list = [];
                byKind[kind] = list;
            }

            list.Add((request, references));
        }

        StringBuilder builder = new();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Threading;");
        builder.AppendLine("using System.Threading.Tasks;");
        builder.AppendLine("using ObsWebSocket.Core.Protocol.Requests;");
        builder.AppendLine("using ObsWebSocket.Core.Protocol.Responses;");
        builder.AppendLine($"using {GeneratedCommonNamespace};");
        builder.AppendLine();
        builder.AppendLine($"namespace {ExtensionsNamespace};");
        builder.AppendLine();

        int emitted = 0;
        foreach (string kind in byKind.Keys.OrderBy(k => k, StringComparer.Ordinal))
        {
            string opsType = OpsTypeName(kind);
            string handleType = HandleTypeForKind(kind);

            builder.AppendLine("/// <summary>");
            builder.AppendLine($"/// Every request about one {DescribeKind(kind)}.");
            builder.AppendLine("/// </summary>");
            builder.AppendLine(
                "/// <param name=\"client\">The client these requests are sent on.</param>"
            );
            builder.AppendLine(
                $"/// <param name=\"handle\">The {DescribeKind(kind)} they are about.</param>"
            );
            builder.AppendLine(
                $"public readonly partial struct {opsType}(ObsWebSocketClient client, {handleType} handle)"
            );
            builder.AppendLine("{");
            builder.AppendLine(
                $"    /// <summary>The {DescribeKind(kind)} these requests address.</summary>"
            );
            builder.AppendLine($"    public {handleType} Handle => handle;");
            builder.AppendLine();

            foreach (
                (RequestDefinition request, IReadOnlyList<EntityReference> refs) in byKind[kind]
                    .OrderBy(r => r.Request.RequestType, StringComparer.Ordinal)
            )
            {
                EmitScopedRequest(context, builder, request, refs);
                builder.AppendLine();
                emitted++;
            }

            builder.AppendLine("}");
            builder.AppendLine();
        }

        builder.AppendLine("/// <summary>");
        builder.AppendLine(
            "/// Addresses one thing in OBS, so the requests about it need not restate which."
        );
        builder.AppendLine("/// </summary>");
        builder.AppendLine("public static class ObsWebSocketHandleExtensions");
        builder.AppendLine("{");
        foreach (string kind in byKind.Keys.OrderBy(k => k, StringComparer.Ordinal))
        {
            builder.AppendLine("    extension(ObsWebSocketClient client)");
            builder.AppendLine("    {");
            builder.AppendLine(
                $"        /// <summary>Every request about one {DescribeKind(kind)}.</summary>"
            );
            builder.AppendLine(
                $"        /// <param name=\"handle\">The {DescribeKind(kind)}, which a name or a uuid converts to.</param>"
            );
            builder.AppendLine(
                $"        public {OpsTypeName(kind)} {AccessorName(kind)}({HandleTypeForKind(kind)} handle) => new(client, handle);"
            );
            builder.AppendLine("    }");
            builder.AppendLine();
        }

        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine($"// Requests reachable through a handle: {emitted}");

        context.AddSource(
            "ObsWebSocketClient.HandleOverloads.g.cs",
            SourceText.From(builder.ToString(), Encoding.UTF8)
        );
    }

    private static string OpsTypeName(string kind) =>
        kind switch
        {
            "sceneItem" => "SceneItemOperations",
            "filter" => "FilterOperations",
            _ => ToPascalCase(kind) + "Operations",
        };

    private static string HandleTypeForKind(string kind) =>
        kind switch
        {
            "sceneItem" => "SceneItemHandle",
            "filter" => "FilterHandle",
            _ => EntityReferenceTable.HandleTypeFor(kind)!,
        };

    private static string AccessorName(string kind) =>
        kind switch
        {
            "sceneItem" => "SceneItem",
            "filter" => "Filter",
            _ => ToPascalCase(kind),
        };

    private static string DescribeKind(string kind) =>
        kind switch
        {
            "sceneItem" => "scene item",
            _ => kind,
        };

    private static void EmitScopedRequest(
        SourceProductionContext context,
        StringBuilder builder,
        RequestDefinition request,
        IReadOnlyList<EntityReference> references
    )
    {
        string baseName = SanitizeIdentifier(request.RequestType);
        string methodName = baseName + "Async";
        string requestDto = $"{GeneratedRequestsNamespace}.{baseName}RequestData";
        bool hasResponse = request.ResponseFields?.Count > 0;
        string returnType = hasResponse
            ? $"Task<{GeneratedResponsesNamespace}.{baseName}ResponseData>"
            : "Task";
        string groupName = ToGroupName(request.Category ?? "general");

        HashSet<string> consumed = new(StringComparer.Ordinal);
        foreach (EntityReference reference in references)
        {
            foreach (string field in reference.Fields)
            {
                _ = consumed.Add(field);
            }
        }

        List<KeyValuePair<string, string>> arguments =
        [
            .. EntityReferenceTable.ArgumentsFor(references[0], "handle"),
        ];

        List<string> required = [];
        List<string> optional = [];
        List<string> docs = [];

        // A second reference, such as the destination of a duplicated scene item, stays a
        // parameter: only one thing can be the subject.
        foreach (EntityReference extra in references.Skip(1))
        {
            string paramName = EntityReferenceTable.ParameterNameForReference(extra);
            required.Add($"{EntityReferenceTable.HandleTypeForReference(extra)} {paramName}");
            docs.Add(
                $"    /// <param name=\"{paramName}\">The {DescribeKind(extra.Kind)} to use.</param>"
            );
            arguments.AddRange(EntityReferenceTable.ArgumentsFor(extra, paramName));
        }

        foreach (FieldDefinition field in request.RequestFields!)
        {
            if (consumed.Contains(field.ValueName))
            {
                continue;
            }

            (string? csharpType, _) = MapProtocolTypeToCSharp(
                context,
                field,
                $"{baseName}RequestData",
                reportDiagnostics: false
            );
            if (csharpType is null)
            {
                continue;
            }

            string paramName = ToCamelCase(SanitizeIdentifier(ToPascalCase(field.ValueName)));
            arguments.Add(new(field.ValueName, paramName));
            docs.Add(
                $"    /// <param name=\"{paramName}\">{System.Security.SecurityElement.Escape(FirstLine(field.ValueDescription))}</param>"
            );

            if (field.ValueOptional == true)
            {
                string suffix = csharpType.EndsWith("?", StringComparison.Ordinal) ? "" : "?";
                optional.Add($"{csharpType}{suffix} {paramName} = null");
            }
            else
            {
                required.Add($"{csharpType} {paramName}");
            }
        }

        builder.AppendLine("    /// <summary>");
        AppendMultiLineXmlDoc(builder, request.Description, "    ///");
        builder.AppendLine("    /// </summary>");
        foreach (string doc in docs)
        {
            builder.AppendLine(doc);
        }

        builder.AppendLine(
            "    /// <param name=\"cancellationToken\">A token to cancel the asynchronous operation.</param>"
        );
        builder.AppendLine(
            hasResponse
                ? "    /// <returns>A task yielding the response data.</returns>"
                : "    /// <returns>A task that completes when OBS has processed the request.</returns>"
        );

        List<string> parameters =
        [
            .. required,
            .. optional,
            "CancellationToken cancellationToken = default",
        ];

        builder.AppendLine($"    public {returnType} {methodName}(");
        builder.AppendLine("        " + string.Join(",\n        ", parameters));
        builder.AppendLine("    ) =>");
        builder.AppendLine($"        client.{groupName}.{methodName}(");
        builder.AppendLine($"            new {requestDto}(");
        builder.AppendLine(
            "                "
                + string.Join(
                    ",\n                ",
                    arguments.Select(a =>
                        $"{ToCamelCase(SanitizeIdentifier(ToPascalCase(a.Key)))}: {a.Value}"
                    )
                )
        );
        builder.AppendLine("            ),");
        builder.AppendLine("            cancellationToken");
        builder.AppendLine("        );");
    }

    private static string FirstLine(string? text) =>
        string.IsNullOrWhiteSpace(text)
            ? "The value to send."
            : text!.Split(['\n', '\r'], StringSplitOptions.RemoveEmptyEntries)[0].Trim();
}
